std_msgs/Header header
bool DIRECTION_FWD = True
bool DIRECTION_REV = False
bool stall_bridge_b False
bool stall_bridge_a False
bool overcurrent False
bool thermal_shutdown False
bool thermal_warning False
bool undervoltage False
bool motor_stopped False
bool motor_accelerating False
bool motor_decelerating False
bool motor_running False
bool motor_direction
bool busy False
bool high_impedance False